models/tournament.py
from google.appengine.api import images
from google.appengine.api import mail
from google.appengine.ext import db
import urllib, math, random

from models import *

class TournamentMembership(db.Model):
  # id = auto
  # parent = tournament
  active = db.BooleanProperty(default=True)
  team   = db.ReferenceProperty(models.Team)
  seed   = db.IntegerProperty()


class TournamentMatchUp(db.Model):
  # key_name = "{round}:{match_seed}"
  # parent = tournament
  next       = db.SelfReferenceProperty()
  
  # this is set when the match is scheduled but not yet played
  match_lookup = db.ReferenceProperty(models.MatchLookup)

  # these are set after the match is played
  # (if the match is a forfeit, winner is set but match is not)
  match  = db.ReferenceProperty(models.Match)
  winner = db.ReferenceProperty(TournamentMembership)

  def schedule_if_ready(self):
    members = self.tournamentmatchupmembership_set.fetch(2)
    assert len(members) == 2

    if all(m.membership for m in members):
      teams = [m.membership.team for m in members]
      self.match_lookup = models.MatchLookup.get_or_insert(
          models.MatchLookup.get_key_name(teams))
      return True
    else:
      return False

  def email(self):
    members = self.tournamentmatchupmembership_set.fetch(2)
    assert len(members) == 2

    tournament = self.parent()
    teams = [m.membership.team for m in members]
    for i in range(2):
      team = teams[i]
      opponent = teams[i^1]

      mail.send_mail(
          sender="tournaments@bb-oftl.appspotmail.com",
          to=team.coach.user.email(),
          bcc="mdekruijf@gmail.com",
          subject="OFTL tournament '%s' match-up notification!" % tournament.key().name(),
          body="""
Your %s %s tournament match with team %s is now scheduled against %s's %s. 
Please contact %s in the OFL/OFTL forums to arrange your match.
          """ % (
            tournament.key().name(),
            self.get_round_name().lower(),
            team.key().name(),
            opponent.coach.key().name(),
            opponent.key().name(),
            opponent.coach.key().name()))

  def advance(self, winner, loser, match=None):
    tournament = self.parent()

    # update the links
    self.match_lookup = None
    self.match = match
    self.winner = winner
    self.put()

    loser.active = False
    loser.put()

    # advance the winner if this was not the final
    if self.next:
      round, seed = [int(x) for x in self.key().name().split(":")]
      mm = TournamentMatchUpMembership.get_by_key_name(
          "%s:%s" % (round + 1, seed), parent=tournament)

      assert mm.match_up.key() == self.next.key()
      mm.membership = winner
      mm.put()

      # schedule the match
      if self.next.schedule_if_ready():
        self.next.put()
        self.next.email()

    else:
      put_list = [tournament, winner]
      tournament.winning_team = winner.team

      # idempotence check
      if winner.active:
        winner.team.tpts += (
            TournamentMembership.all().ancestor(tournament).count() - 1)
        coach_stats = CoachStats.all().ancestor(winner.team.coach).get()
        coach_stats.tpts += (
            TournamentMembership.all().ancestor(tournament).count() - 1)

        leader = models.CoachLeader.get_by_key_name("Silverware")
        coach_standing = models.CoachLeaderStanding(
            key_name = winner.team.coach.key().name(),
            parent   = leader,
            coach_stats     = coach_stats,
            score    = leader.get_score(coach_stats))

        leader = models.TeamLeader.get_by_key_name("Silverware")
        leader_standing = models.TeamLeaderStanding(
            key_name = winner.team.key().name(),
            parent   = leader,
            team     = winner.team,
            score    = leader.get_score(winner.team))
        put_list.extend([winner.team, leader_standing, coach_stats, coach_standing])

      winner.active = False
      db.put(put_list)


  def get_round_name(self):
    max_seed = 0
    for mm in self.tournamentmatchupmembership_set:
      max_seed = max(max_seed, int(mm.key().name().split(":")[1]))

    round = int(math.log(max_seed, 2))
    map = {
        0: "Final",
        1: "Semi-final",
        2: "Quarter-final",
        3: "Round of 16",
        4: "Round of 32",
        5: "Round of 64",
        }

    return map[round]


class TournamentMatchUpMembership(db.Model):
  # key_name = "{round}:{team_seed}"
  # parent = tournament
  match_up   = db.ReferenceProperty(TournamentMatchUp)
  membership = db.ReferenceProperty(TournamentMembership)


class TournamentPicture(db.Model):
  # key_name = tournament title
  box     = db.BlobProperty()
  cabinet = db.BlobProperty()
  thumb   = db.BlobProperty()

  @classmethod
  def create_from_img(cls, key_name, pic):
    box     = db.Blob(images.resize(pic, 600, 300))
    cabinet = db.Blob(images.resize(pic, 80, 40))
    thumb   = db.Blob(images.resize(pic, 32, 16))
    return cls(key_name=key_name, box=box, cabinet=cabinet, thumb=thumb)


class Tournament(db.Model):
  # key_name = title
  created   = db.DateTimeProperty(auto_now_add=True)
  owner     = db.ReferenceProperty(models.Coach)

  background = db.TextProperty()
  pic        = db.ReferenceProperty(TournamentPicture)

  started      = db.BooleanProperty(default=False)
  winning_team = db.ReferenceProperty(models.Team)

  min_tv    = db.IntegerProperty()
  max_tv    = db.IntegerProperty()
  min_ma    = db.IntegerProperty()
  max_ma    = db.IntegerProperty()

  max_enrollment = db.IntegerProperty()
  seed_by        = db.StringProperty(choices=('Random', 'TV', 'AWP', 'Rating', 'Custom'))
  races_allowed  = db.ListProperty(db.Key)

  def get_box_href(self):
    return '#tournament?tournament_key_name=%s' % urllib.quote(self.key().name())

  def schedule(self):
    assert not self.started, "Tournament already started?!"

    # cache the members of the tournament in a list
    members = list(TournamentMembership.all().ancestor(self))

    # order members by seed
    if self.seed_by == "Custom":
      members.sort(key = lambda m: m.seed)

      for i, member in enumerate(members):
        assert member.seed == i

    else:
      if self.seed_by == "Random":
        random.shuffle(members)
      else:
        seed_attr = self.seed_by.lower()
        if self.seed_by == "Rating":
          seed_attr = "glicko_r"

        members.sort(
            key = lambda m: getattr(m.team, seed_attr),
            reverse=True)

      for i, member in enumerate(members):
        member.seed = i
        member.put()

    # create the match ups for each round
    num_teams  = len(members)
    num_rounds = int(math.ceil(math.log(num_teams, 2)))
    
    # update tournament
    self.started = True
    self.final = db.Key.from_path(
        "Tournament", self.key().name(),
        "TournamentMatchUp", "%s:0" % (num_rounds - 1))
    self.put()

    # iterate over the rounds in order from wildcards to finals
    scheduled_seeds = set()

    for round in range(num_rounds):
      matches_in_round    = 2**(num_rounds - 1 - round)

      def get_next_match_up(seed):
        if round == num_rounds - 1:
          return None
        else:
          if seed < matches_in_round / 2:
            next_seed = seed
          else:
            next_seed = matches_in_round - 1 - seed

          return db.Key.from_path(
              "Tournament", self.key().name(),
              "TournamentMatchUp", "%s:%s" % (round + 1, next_seed))

      # create the match ups for this round and schedule the teams if they are
      # not already scheduled in a previous round
      for seed in range(matches_in_round):

        high_seed = seed
        low_seed  = 2*matches_in_round - 1 - seed
        if low_seed >= num_teams:
          # then we are in the wildcard round and this match doesn't exist
          continue

        match_up = TournamentMatchUp(
            key_name     = "%s:%s" % (round, seed),
            parent       = self,
            next         = get_next_match_up(seed))
        match_up.put()

        for team_seed in (high_seed, low_seed):
          mm = TournamentMatchUpMembership(
              key_name   = "%s:%s" % (round, team_seed),
              parent     = self,
              match_up   = match_up,
              seed       = team_seed)
          if not team_seed in scheduled_seeds:
            scheduled_seeds.add(team_seed)
            mm.membership = members[team_seed]

          mm.put()

        if match_up.schedule_if_ready():
          match_up.put()
          match_up.email()

views/coach_box.py
from google.appengine.ext import db
from google.appengine.ext import webapp
from operator import attrgetter

from models import Team, CoachStats, Coach, TeamRecord
import misc, views
from misc.table import Table, Column


class CoachBox(views.CachedView):

  def get(self):

    # check for a cached version
    #--------------------------------------------------------------------#

    coach_key = db.Key.from_path("Coach", self.request.get("coach_key_name"))
    if self.emit(self.response.out, coach_key):
      return

    # not cached or evicted from cache; regenerate
    #--------------------------------------------------------------------#

    coach = Coach.get(coach_key)
    if not coach:
      return

    coach_stats = CoachStats.all().ancestor(coach).get()
    # win/draw/loss bars and banner text color
    #--------------------------------------------------------------------#

    longest_bar_length = max(coach_stats.wins, coach_stats.draws, coach_stats.losses)
    banner_text_color = misc.get_contrasting_monochrome(coach.color)

    # team_table
    #--------------------------------------------------------------------#

    def name_getter(team):
      return "<a rel='team' href='%s'>%s</a>" % (
          team.get_box_href(), team.key().name())

    def race_getter(team):
      return "<img title='%s' src='%s' />" % (
          team.race.key().name(), team.race.get_image_src(thumb=True))

    def awp_getter(team):
      return "%0.3f" % team.awp

    def glicko_getter(team):
      return "%4.0f" % team.glicko_r
    
    teams = query = Team.all().filter("coach =", coach).filter("matches >", 0).order("-matches")
    team_table = Table(
          columns = [
            # profile
            Column(" ",         "Race",               race_getter, center=True),
            Column("Team Name", "Team name",          name_getter),
            Column("TV",        "Team value (approximate)",
              attrgetter("tv"), divider=True),

            # record
            Column("Pl",        "Matches played",     attrgetter("matches")),
            Column("W",         "Matches won",        attrgetter("wins")),
            Column("D",         "Matches drawn",      attrgetter("draws")),
            Column("L",         "Matches lost",       attrgetter("losses"),
              divider=True),

            # rankings
            Column("AWP",       "Adjusted win percentage", awp_getter),
            Column("TPts",      "Tournament Points",       attrgetter("tpts")),
            Column("Rating",    "Glicko Rating",           glicko_getter,
              divider=True),

            ## touchdowns
            #Column("TD+",       "Touchdowns for",     attrgetter("tds_for")),
            #Column("TD-",       "Touchdowns against", attrgetter("tds_against")),
            #Column("<span class='over'>TD+</span>",  "Average touchdowns for",
            #  get_ave_getter("tds_for")),
            #Column("<span class='over'>TD-</span>",  "Average touchdowns against",
            #  get_ave_getter("tds_against")),

            ## casualties
            #Column("C+",        "Casualties for",     attrgetter("cas_for")),
            #Column("C-",        "Casualties against", attrgetter("cas_against")),
            #Column("<span class='over'>C+</span>",  "Average casualties for",
            #  get_ave_getter("cas_for")),
            #Column("<span class='over'>C-</span>",  "Average casualties against",
            #  get_ave_getter("cas_against")),
            ],
          query = teams,
          id = "%s-team-table" % coach.key(),
          cls = "tablesorter",
          )


    # coach_stat_table
    #--------------------------------------------------------------------#

    def get_left_header(tuple):
      coach_stats, which = tuple
      return which.capitalize()

    def getter(stat):
      def getter_closure(tuple):
        coach_stats, which = tuple
        attr = getattr(coach_stats, "%s_%s" % (stat, which))
        return (
            ("<span class='tot_stat'>%d</span>" % attr) +
            ("<span class='ave_stat'>%.1f</span>" % (attr / float(coach_stats.matches))))

      return getter_closure

    stat_table = Table(
        columns = [
          Column("<span class='link' id='%s-show-averages-toggle'></span>" %
            coach.key(), "", get_left_header),
          Column("TD", "Touchdowns",       getter("tds")),
          Column("P",  "Pass completions", getter("passes")),
          Column("YP", "Yards passing",    getter("pyards")),
          Column("R",  "Pass receptions",  getter("rec")),
          Column("YR", "Yards rushing",    getter("ryards")),
          Column("K",  "Kills",            getter("kills")),
          Column("C",  "Casualties",       getter("cas")),
          Column("KO", "Knock outs",       getter("ko")),
          Column("S",  "Stuns",            getter("stun")),
          Column("T",  "Tackles",          getter("tckl")),
          Column("I",  "Interceptions",    getter("int")),
          ],
        query = ((coach_stats, "for"), (coach_stats, "against")),
        cls = "fancytable stats",
        )

    # render and update (TODO: move to bottom after implementing bottom code)
    #--------------------------------------------------------------------#

    coach_box = misc.render('coach_box.html', locals())
    self.update(coach_box, coach_key)

    self.response.out.write(coach_box)
'''
    # match_tables
    #--------------------------------------------------------------------#

    def name_getter(record):
      if record.team.key() == team.key():
        return team.key().name()
      else:
        return "<a rel='team_opponents' href='%s'>%s</a>" % (
            record.team.get_box_href(), record.team.key().name())

    def race_getter(record):
      return "<img src='%s' />" % record.team.race.get_image_src(thumb=True)

    def link_getter(record):
      return """
      <a rel='team_matches' href='%s'>
      <span class="go_to_arrow" title='Go to match page'>&rarr;</span></a>""" % (
          record.get_match().get_box_href())

    def glicko_getter(record):
      return "%4.0f" % record.glicko_r

    match_columns = [
        Column(" ",         "Race",             race_getter,
          center=True),
        Column("Team",      "Team name",        name_getter),
        Column("Rating",    "Team rating",      glicko_getter),
        Column("TV",        "Team value",       attrgetter("tv_for")),
        Column("TD",        "Touchdowns",       attrgetter("tds_for")),
        Column("P",         "Pass completions", attrgetter("passes_for")),
        Column("YP",        "Yards passing",    attrgetter("pyards_for")),
        Column("R",         "Pass receptions",  attrgetter("rec_for")),
        Column("YR",        "Yards rushing",    attrgetter("ryards_for")),
        Column("K",         "Kills",            attrgetter("kills_for")),
        Column("C",         "Casualties",       attrgetter("cas_for")),
        Column("KO",        "Knock outs",       attrgetter("ko_for")),
        Column("S",         "Stuns",            attrgetter("stun_for")),
        Column("T",         "Tackles",          attrgetter("tckl_for")),
        Column("I",         "Interceptions",    attrgetter("int_for")),
        Column("", "", link_getter, center=True, rowspan=2)
        ]

    # get matches from match_records and sort in order of most recent
    for team in teams:
      matches = sorted(
          [record.get_match() for record in team.teamrecord_set],
          key=lambda m: m.created, reverse=True)

    match_tables = []
    for match in matches:
      # sort with this team's match record first
      match_records = sorted(
          match.get_team_records_query(),
          key=lambda mr: mr.team.key() == team.key(),
          reverse=True)

      result_map = {
          1  : "WIN!",
          0  : "DRAW",
          -1 : "LOSS"}

      title = "(%s) <b>%s-%s %s</b> vs. %s" % (
          match.created.date(),
          match_records[0].tds_for,
          match_records[1].tds_for,
          result_map[match_records[0].result],
          match_records[1].team.key().name())

      if match.disconnect:
        title += " (Disconnect/Forfeit)"

      match_table = Table(
          columns = match_columns,
          query = match_records,
          cls = "tablesorter match_stats",
          title = title)

      match_tables.append((match.get_box_href(), match_table))
'''
#    active_member = team.get_active_tournament_membership()
#    active_tournament = active_member.parent() if active_member else None

templates/coach_box.html
<style type="text/css">

div.team_box div.banner {
  background-color: {{ coach.color }};
  color: {{ banner_text_color }};
}

</style>

<script type="text/javascript">

$(function() {
  $('#{{ coach.key }}-matches').accordion();

  // don't do this -- think of the match link:
  // $('.match_stats').tablesorter();

  $('#{{ team_table.id }}').tablesorter({
    sortInitialOrder: "desc",
    sortList: [[0,0]]
  });

  $("#{{ coach.key }}-show-averages-toggle").html("Total")
  .toggle(function () {
    $(this).html("Average")
    $('.tot_stat').fadeOut(500, function() {
      $('.ave_stat').fadeIn(500);
    });
  }, function () {
    $(this).html("Total")
    $('.ave_stat').fadeOut(500, function() {
      $('.tot_stat').fadeIn(500);
    });
  });

  $('a[rel="trophy_tournaments"]').colorbox({
    current: "",
    href: function() { return $(this).attr('href').replace("#", ""); },
    copy: true,
    scrolling: false
  });

  $('a[rel="team_tournaments"]').colorbox({
    current: "",
    href: function() { return $(this).attr('href').replace("#", ""); },
    copy: true,
    scrolling: false
  });

  $('a[rel="team_opponents"]').colorbox({
    current: "",
    href: function() { return $(this).attr('href').replace("#", ""); },
    copy: true,
    scrolling: false
  });

  $('a[rel="team_matches"]').colorbox({
    current: "",
    href: function() { return $(this).attr('href').replace("#", ""); },
    copy: true,
    scrolling: false
  });
  
  $('a[rel="team"]').colorbox({
    current: "",
    href: function() { return $(this).attr('href').replace("#", ""); },
    scrolling: false
  });

  $('a[rel="team_players"]').colorbox({
    current: "",
    href: function() { return $(this).attr('href').replace("#", ""); },
    copy: true,
    scrolling: false
  });

  $('.hidden').hide()
  $('div.show_hidden .link').click(function () {
    $('div.hidden').show();
    $(this).hide();
    $.fn.colorbox.resize();
  });

  var win_width  = (325 * {{ coach_stats.wins }} / {{ longest_bar_length }}) + "px";
  var draw_width = (325 * {{ coach_stats.draws }} / {{ longest_bar_length }}) + "px";
  var loss_width = (325 * {{ coach_stats.losses }} / {{ longest_bar_length }}) + "px";

  $('#{{ coach.key }}-win-bar' ).animate( { width: win_width  }, 1500, "easeOutCirc");
  $('#{{ coach.key }}-draw-bar').animate( { width: draw_width }, 1500, "easeOutCirc");
  $('#{{ coach.key }}-loss-bar').animate( { width: loss_width }, 1500, "easeOutCirc");
});

</script>


<div class="team_box box">
  <div class="banner">
    <img class="logo_left"  src="{{ coach.get_logo_url }}" />
    <img class="logo_right" src="{{ coach.get_logo_url }}" />
    <span class="title">{{ coach.key.name }}</span>
  </div>

  <div class="info">

    <!-- race right float -->
    <img class="race" src="{{ coach.get_logo_url }}" />

    <!-- center graph -->
    <table class="graph">
      <tbody>
        <tr>
          <td>W</td>
          <td><div id="{{ coach.key }}-win-bar" class="bar green_bg green_border"></div></td>
        </tr>
        <tr>
          <td>D</td>
          <td><div id="{{ coach.key }}-draw-bar" class="bar yellow_bg yellow_border"></div></td>
        </tr>
        <tr>
          <td>L</td>
          <td><div id="{{ coach.key }}-loss-bar" class="bar red_bg red_border"></div></td>
        </tr>
      </tbody>
    </table>

    <!-- profile -->
    <table class="profile">
      <tbody> 
		<tr>
          <td title="Adjusted Win Percentage">AWP:</td>
          <td>{{ coach_stats.awp }}</td>
        </tr>		
		<tr>
          <td title="Record">Record:</td>
          <td>{{ coach_stats.wins }} - {{ coach_stats.draws }} - {{ coach_stats.losses }}</td>
        </tr>
		<tr>
          <td title="Matches">Matches:</td>
          <td>{{ coach_stats.matches }}</td>
        </tr>
        <tr>
          <td title="Tournament Points">Tournament Points:</td>
          <td>{{ coach_stats.tpts }}</td>
        </tr>
        <tr>
        <tr>
          <td title="Total Touchdowns">Total Touchdowns:</td>
          <td>{{ coach_stats.tds_for }}</td>
        </tr>
		<tr>
          <td title="Total Touchdowns">Touchdowns Allowed:</td>
          <td>{{ coach_stats.tds_against }}</td>
        </tr>
		<tr>
          <td title="Total Casualties Inflicted Against Opponents">Casualties Inflicted:</td>
          <td>{{ coach_stats.cas_for }}</td>
        </tr>
		<tr>
          <td title="Total Casualties Suffered By Opponents">Casualties Suffered:</td>
          <td>{{ coach_stats.cas_against }}</td>
        </tr>
      </tbody>
    </table>
  </div>

  {% if coach_stats.tpts %}
  <div class="h2">
    <h2>Trophy Cabinet</h2>
  </div>
  <div class="trophies">
    {% for team in coach.team_set %}
      {% for tournament in team.tournament_set %}
    
      <div class="trophy">
        {% if tournament.pic %}
        <img src='get_trophy?size=cabinet&tournament_key={{ tournament.key }}' />
        {% else %}
        <div class="no_img_text">
          no image
        </div>
        {% endif %}
        <br />
        <a rel="trophy_tournaments" href="{{tournament.get_box_href }}">
          {{ tournament.key.name }}</a>
      </div>
	  {% endfor %}
    {% endfor %}
    <br style="clear: both" />
  </div>
  {% endif %}

  {% if coach.bio %}
  <div class="h2">
    <h2>Biography</h2>
  </div>
  <p>
    {{ coach.bio|linebreaks }}
  </p>
  {% endif %}

  <div class="h2">
    <h2>Teams</h2>
  </div>
  {% with team_table as table %}
  {% include "table.html" %}
  {% endwith %}

  <div class="show_hidden">
    <span class="link">more</span>
  </div>

  <div class="hidden">
    <div class="h2">
      <h2>Coach Statistics</h2>
    </div>
    {% with stat_table as table %}
    {% include "table.html" %}
    {% endwith %}


    <div class="h2">
      <h2>Match History</h2>
    </div>

    <div class="team_matches" id="{{ coach.key }}-matches">
      {% for href, match_table in match_tables %}
      <h3><a href="#"> {{ match_table.title|safe }} </a></h3>
      <div class="team_match">
        {% with match_table as table %}
        {% include "table.html" %}
        {% endwith %}
      </div>
      {% endfor %}
    </div>

  </div>
</div>

templates/coach_leaders.html
{% extends "leaders.html" %}

{% block javascript %}
  $('a[rel="leader_coach"]').colorbox({
    current: "",
    href: function() { return $(this).attr('href').replace("#", ""); },
    scrolling: false
  });
{% endblock %}

templates/leaders.html
<script type="text/javascript">
  analytics();

{% block javascript %}
{% endblock %}
                                                 
$(function() {
  $('.leader_table tbody').hover(function() {
    var leader_section = $(this).parents("div.leader_section");
    var stats = leader_section.find(".leader_stats")
    stats.stop(true, true).toggle(500);
    var box = leader_section.find(".leader_box_active");
    box.stop(true, true).toggle(200);
  });

  $('.leader_table tr').hover(function() {
    var leader_section = $(this).parents("div.leader_section");
    var row_number = $(this).attr("class").split("_")[1];

    var box = leader_section.find(".leader_box_" + row_number);
    leader_section.find(".leader_box_active").html(box.html()).css(
      "background-color", box.css("background-color"));

    var info = leader_section.find(".leader_info_" + row_number);
    info.toggle();
  });
});

</script>

{% for leader, leader_table, leader_stats_table, leaders, leader_names in leader_info %}
<div class="h2">
  <h2> {{ leader.top_text }} {{ leader.key.name }} </h2>
</div>
<p>
<i>
Formula: {{ leader.formula }}
</i>
</p>

<div class="leader_section">
{% with leader_table as table %}
{% include "table.html" %}
{% endwith %}

<div class="leader_stats">
<div class="leader_name"> &nbsp; 
{% for leader_name in leader_names %}
<span class="leader_info leader_info_{{ forloop.counter }}">
  {{ leader_name|safe }}
</span>
{% endfor %}
</div>
{% with leader_stats_table as table %}
{% include "table.html" %}
{% endwith %}
</div>

{% block boxes %}
{% endblock %}

</div>
{% endfor %}

templates/league_standings.html
<script type="text/javascript">
$(function() {
  analytics();
  $('a[rel="coach"]').colorbox({
    current: "",
    href: function() { return $(this).attr('href').replace("#", ""); },
    scrolling: false
  });
  $('a[rel="team"]').colorbox({
    current: "",
    href: function() { return $(this).attr('href').replace("#", ""); },
    scrolling: false
  });
  $('.tablesorter').tablesorter();
});
</script>

<p>
The OFTL ranks teams along three metrics:
Adjusted Winning Percentage, Tournament Points. and Glicko Rating. 
Details on each of the three can be found on the forums in the
<a href="http://www.shalkith.com/bloodbowl/forum/viewtopic.php?f=13&t=4">OFTL League Rules and FAQ</a>.
</p>
<p>
A team's listed Team Value (TV) is an estimate based on the TV from the previous
match with an extra 20 points for every pending level-up.
For fairness in tournament enrollment, the TV includes the values of <i>all</i>
current players, including those who are out for the next match.
</p>
<p>
The table below is sortable by column (as are most of the other tables on the
site). 
To sort by multiple columns, shift-click additional sort columns.
</p>

<div class="h2">
<h2>Active Team Listing</h2>
</div>
{% with tables.active as table %}
{% include "table.html" %}
{% endwith %}

{% comment %}
<div class="h2">
<h2>Retired Team Listing</h2>
</div>
{% with tables.retired as table %}
{% include "table.html" %}
{% endwith %}
{% endcomment %}

templates/match_box.html
<script type="text/javascript">
$(function() {
  $('a[rel="match_teams"]').colorbox({
    current: "",
    href: function() { return $(this).attr('href').replace("#", ""); },
    copy: true,
    scrolling: false
  });
  $('a[rel="match_tournaments"]').colorbox({
    current: "",
    href: function() { return $(this).attr('href').replace("#", ""); },
    copy: true,
    scrolling: false
  });
  $('a[rel="match_players"]').colorbox({
    current: "",
    href: function() { return $(this).attr('href').replace("#", ""); },
    copy: true,
    scrolling: false
  });

  $('.team_match_table').tablesorter();
  $('.player_match_table').tablesorter({
    sortList: [[0,0]]
  });
  $('.injury_table').tablesorter();
});
</script>

<div class="box match_box">
{% include "match_header.html" %}

<div class="h2">
  <h2>Team Statistics</h2>
</div>
{% with team_match_table as table %}
{% include "table.html" %}
{% endwith %}

<div class="h2">
  <h2>Player Statistics</h2>
</div>
<script type="text/javascript">
  $(function() {
    $('.match_player_tables').accordion({
      autoHeight: false,
      change: function() { $.fn.colorbox.resize() }
    });
  });
</script>
<div class="match_player_tables">
  {% for team, table in player_match_tables %}
  <h3><a href="#"> {{ team }} </a></h3>
  <div>
    {% include "table.html" %}
  </div>
  {% endfor %}
</div>

{% if injury_table %}
<div class="h2">
  <h2>Player Casualties</h2>
</div>
{% with injury_table as table %}
{% include "table.html" %}
{% endwith %}
{% endif %}

</div>

templates/player_leaders.html
{% extends "leaders.html" %}

{% block javascript %}
  $('a[rel="leader_player"]').colorbox({
    current: "",
    href: function() { return $(this).attr('href').replace("#", ""); },
    scrolling: false
  });
{% endblock %}

{% block boxes %}
<div class="leader_box leader_box_active"></div>
{% for player in leaders %}
  <div class="leader_box leader_box_{{ forloop.counter }}">
    <img class="player_img" src='{{ player.get_leader_pic_url }}' />
  </div>
{% endfor %}
{% endblock %}